# Generated by Django 6.0.1 on 2026-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
